version: '3.4'

services:
  data_service:
    image: ${DOCKER_REGISTRY-}dataservice
    build:
      context: .
      dockerfile: Data_Service/Dockerfile
    depends_on:
      - mongo
    restart: always
    ports:
     - 5000:80

  sensor_device_service:
    image: ${DOCKER_REGISTRY-}sensordeviceservice
    build:
      context: .
      dockerfile: Sensor_Device_Service/Dockerfile
    restart: always
    ports:
     - 5001:80

  mongo:
    image: mongo
    restart: always
    ports:
      - 27117:27017

  mongoAnalytics:
    image: mongo
    restart: always
    ports:
      - 27119:27017

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    restart: always

  analytics_service:
    image: ${DOCKER_REGISTRY-}analyticsservice
    build:
      context: .
      dockerfile: Analytics_Service/Dockerfile
    depends_on: 
    - rabbitmq
    - mongoAnalytics
    ports:
     - 5002:80

  command_service:
    image: ${DOCKER_REGISTRY-}commandservice
    build:
      context: .
      dockerfile: Command_Service/Dockerfile
    depends_on: 
    - rabbitmq
    ports:
     - 5003:80

  api_gateway_service:
    image: ${DOCKER_REGISTRY-}apigatewayservice
    build:
      context: .
      dockerfile: API_Gateway_Service/Dockerfile
    ports:
     - 5004:80

  webdashboard:
    image: ${DOCKER_REGISTRY-}webdashboard
    build:
      context: .
      dockerfile: WebDashboard/Dockerfile
    depends_on: 
    - data_service
    - command_service
    - api_gateway_service
    restart: always