version: '3.4'

services:
  data_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  sensor_device_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  analytics_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  command_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  api_gateway_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  webdashboard:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
