version: '3.4'

services:
  data_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  sensor_device_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

